# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: AlveSvaren.Resizer2
PackageVersion: 2.0.1
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/alvesvaren/resizer2/releases/download/v2.0.1/resizer2-setup.exe
  InstallerSha256: 04C655B035745170E51D0FA0E3B52FB1CD09E37F462C12174D73163C851C7E66
ManifestType: installer
ManifestVersion: 1.10.0
